  CREATE TABLE "ADMINISTRADOR" 
   (	"COD_ADM" NUMBER, 
	"COD_USUARIO" NUMBER NOT NULL ENABLE, 
	"NOME" VARCHAR2(100) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(100), 
	 PRIMARY KEY ("COD_ADM")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "AGENDAMENTOS" 
   (	"COD_AGENDAMENTO" NUMBER, 
	"ALOCACAO" VARCHAR2(50), 
	"DATA" DATE, 
	"COD_CLIENTE" NUMBER NOT NULL ENABLE, 
	 PRIMARY KEY ("COD_AGENDAMENTO")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "CLIENTE" 
   (	"COD_CLIENTE" NUMBER, 
	"COD_USUARIO" NUMBER NOT NULL ENABLE, 
	"NOME" VARCHAR2(100) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(100), 
	"ENDERECO" VARCHAR2(200), 
	 PRIMARY KEY ("COD_CLIENTE")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "CONSULTA" 
   (	"COD_CONSULTA" NUMBER, 
	"DATA_CRIACAO" DATE NOT NULL ENABLE, 
	"DATA_CONSULTA" DATE NOT NULL ENABLE, 
	"CUSTO" NUMBER(10,2), 
	"ALOCADO" VARCHAR2(50), 
	"COD_CLIENTE" NUMBER NOT NULL ENABLE, 
	"COD_INSTITUICAO" NUMBER NOT NULL ENABLE, 
	"COD_PROFISSIONAL" NUMBER NOT NULL ENABLE, 
	 PRIMARY KEY ("COD_CONSULTA")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "INSTITUICAO" 
   (	"COD_INSTITUICAO" NUMBER, 
	"NOME" VARCHAR2(100) NOT NULL ENABLE, 
	"TIPO" VARCHAR2(50), 
	 PRIMARY KEY ("COD_INSTITUICAO")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "PROFISSIONAL" 
   (	"COD_PROFISSIONAL" NUMBER, 
	"COD_INSTITUICAO" NUMBER NOT NULL ENABLE, 
	"NOME" VARCHAR2(100) NOT NULL ENABLE, 
	"NUMERO" VARCHAR2(20), 
	"EMAIL" VARCHAR2(100), 
	 PRIMARY KEY ("COD_PROFISSIONAL")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "USUARIO" 
   (	"COD_USUARIO" NUMBER, 
	"NOME" VARCHAR2(100) NOT NULL ENABLE, 
	"SENHA" VARCHAR2(50) NOT NULL ENABLE, 
	"CADASTRO" DATE, 
	"LOGIN" DATE, 
	 PRIMARY KEY ("COD_USUARIO")
  USING INDEX  ENABLE
   ) ;


  CREATE UNIQUE INDEX "SYS_C00167112081" ON "USUARIO" ("COD_USUARIO") 
  ;

  CREATE UNIQUE INDEX "SYS_C00167112125" ON "INSTITUICAO" ("COD_INSTITUICAO") 
  ;

  CREATE UNIQUE INDEX "SYS_C00167112130" ON "CLIENTE" ("COD_CLIENTE") 
  ;

  CREATE UNIQUE INDEX "SYS_C00167112133" ON "ADMINISTRADOR" ("COD_ADM") 
  ;

  CREATE UNIQUE INDEX "SYS_C00167112137" ON "PROFISSIONAL" ("COD_PROFISSIONAL") 
  ;

  CREATE UNIQUE INDEX "SYS_C00167112144" ON "CONSULTA" ("COD_CONSULTA") 
  ;

  CREATE UNIQUE INDEX "SYS_C00167112149" ON "AGENDAMENTOS" ("COD_AGENDAMENTO") 
  ;



   CREATE SEQUENCE  "USUARIO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 7 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;







